Thu Dec  7 20:13:34 2023
KeyError
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 22, in search_command_handler
    data["search_cond"] = msg_user
    ~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\exception_handler.py", line 21, in wrapped
    method(message)
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 21, in search_command_handler
    with bot.retrieve_data(user_id=user_id, chat_id=chat_id) as data:
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\base_storage.py", line 68, in __exit__
    return self.obj.save(self.chat_id, self.user_id, self.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\memory_storage.py", line 69, in save
    self.data[chat_id][user_id]['data'] = data
    ~~~~~~~~~^^^^^^^^^
KeyError: 439024736



Fri Dec  8 16:31:21 2023
KeyError
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 22, in search_command_handler
    data["search_cond"] = msg_user
    ~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\exception_handler.py", line 21, in wrapped
    method(message)
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 21, in search_command_handler
    with bot.retrieve_data(user_id=user_id, chat_id=chat_id) as data:
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\base_storage.py", line 68, in __exit__
    return self.obj.save(self.chat_id, self.user_id, self.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\memory_storage.py", line 69, in save
    self.data[chat_id][user_id]['data'] = data
    ~~~~~~~~~^^^^^^^^^
KeyError: 439024736



Fri Dec  8 16:36:12 2023
KeyError
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 22, in search_command_handler
    data["search_cond"] = msg_user
    ~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\exception_handler.py", line 21, in wrapped
    method(message)
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 21, in search_command_handler
    with bot.retrieve_data(user_id=user_id, chat_id=chat_id) as data:
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\base_storage.py", line 68, in __exit__
    return self.obj.save(self.chat_id, self.user_id, self.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\memory_storage.py", line 69, in save
    self.data[chat_id][user_id]['data'] = data
    ~~~~~~~~~^^^^^^^^^
KeyError: 439024736



Fri Dec  8 16:39:46 2023
KeyError
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 22, in search_command_handler
    data["search_cond"] = msg_user
    ~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\exception_handler.py", line 21, in wrapped
    method(message)
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 21, in search_command_handler
    with bot.retrieve_data(user_id=user_id, chat_id=chat_id) as data:
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\base_storage.py", line 68, in __exit__
    return self.obj.save(self.chat_id, self.user_id, self.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\memory_storage.py", line 69, in save
    self.data[chat_id][user_id]['data'] = data
    ~~~~~~~~~^^^^^^^^^
KeyError: 439024736



Fri Dec  8 16:41:28 2023
KeyError
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 22, in search_command_handler
    data["search_cond"] = msg_user
    ~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\exception_handler.py", line 21, in wrapped
    method(message)
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\search_commands.py", line 21, in search_command_handler
    with bot.retrieve_data(user_id=user_id, chat_id=chat_id) as data:
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\base_storage.py", line 68, in __exit__
    return self.obj.save(self.chat_id, self.user_id, self.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\memory_storage.py", line 69, in save
    self.data[chat_id][user_id]['data'] = data
    ~~~~~~~~~^^^^^^^^^
KeyError: 439024736



Fri Dec  8 18:16:23 2023
KeyError
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\additional_handlers\price_rating.py", line 19, in main_search_command
    data["cond2"] = "_less_than"
    ~~~~^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\default_handlers\exception_handler.py", line 21, in wrapped
    method(message)
  File "C:\Users\user\PycharmProjects\python_basic_diploma\handlers\additional_handlers\price_rating.py", line 17, in main_search_command
    with bot.retrieve_data(user_id=user_id, chat_id=chat_id) as data:
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\base_storage.py", line 68, in __exit__
    return self.obj.save(self.chat_id, self.user_id, self.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\python_basic_diploma\venv\Lib\site-packages\telebot\storage\memory_storage.py", line 69, in save
    self.data[chat_id][user_id]['data'] = data
    ~~~~~~~~~^^^^^^^^^
KeyError: 439024736



